version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: scorpil/rust:1.18
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: cargo test